AllCops:
  RunRailsCops: true
  Exclude:
    - 'db/**/*'
    - 'config/unicorn.rb'
    - 'bin/setup'
    - 'vendor/**/*'
    - 'test/**/*'
    - 'tmp/**/*'

Lint/EndAlignment:
  Enabled: false

Style/CaseIndentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ElseAlignment:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

# allow "self.new"
Style/RedundantSelf:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/AsciiComments:
  Enabled: false

# ----------------

# Offense count: 7
# Configuration parameters: CountComments.
Metrics/ClassLength:
  Exclude:
    - 'app/models/*'
    - 'app/controllers/viewer_controller.rb'
    - 'lib/arcana_searcher.rb'
    - 'lib/arcana_importer.rb'

# Offense count: 12
# Configuration parameters: Include.
Rails/Output:
  Exclude:
    - 'lib/arcana_importer.rb'

# Offense count: 18
Metrics/AbcSize:
  Max: 161

# Offense count: 13
Metrics/CyclomaticComplexity:
  Max: 44

# Offense count: 87
# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 155

# Offense count: 22
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 118

# Offense count: 9
Metrics/PerceivedComplexity:
  Max: 35

# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: Width.
Style/IndentationWidth:
  Exclude:
    - 'lib/arcana_searcher.rb'
