AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/unicorn.rb'
    - 'bin/setup'
    - 'vendor/**/*'
    - 'test/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Bundler/OrderedGems:
  Enabled: false

Lint/EndAlignment:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

# allow "self.new"
Style/RedundantSelf:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails:
  Enabled: true

# ----------------

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Exclude:
    - 'app/models/*'
    - 'lib/arcana_searcher.rb'
    - 'lib/arcana_importer.rb'
    - 'lib/arcana_cache.rb'

# Configuration parameters: Include.
Rails/Output:
  Exclude:
    - 'lib/arcana_importer.rb'

Metrics/AbcSize:
  Max: 60
  Exclude:
    - 'lib/arcana_searcher.rb'
    - 'lib/arcana_importer.rb'

Metrics/CyclomaticComplexity:
  Max: 45

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 140
  Exclude:
    - 'lib/arcana_importer.rb'

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 60
  Exclude:
    - 'lib/arcana_searcher.rb'
    - 'lib/arcana_importer.rb'

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'lib/arcana_searcher.rb'
    - 'lib/arcana_importer.rb'

# Configuration parameters: Width.
Layout/IndentationWidth:
  Exclude:
    - 'lib/arcana_searcher.rb'

Metrics/BlockLength:
  Exclude:
    - 'lib/arcana_searcher.rb'
    - 'lib/arcana_importer.rb'
    - 'lib/tasks/*'
    - 'lib/redis_cache/*'
