require:
  - rubocop-rails

AllCops:
  Exclude:
    - "db/**/*"
    - "bin/**/*"
    - "vendor/**/*"
    - "test/**/*"
    - "tmp/**/*"
    - "node_modules/**/*"
    - "config/deploy.rb"
    - "config/deploy/*"
  TargetRubyVersion: 2.6
  DisplayCopNames: true

Bundler/OrderedGems:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

# allow "self.new"
Style/RedundantSelf:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Rails:
  Enabled: true

Rails/HasManyOrHasOneDependent:
  Enabled: false

# TODO: delete & apply
Rails/FilePath:
  EnforcedStyle: "arguments"

# Metrics --------------------

Metrics/LineLength:
  Max: 120

Metrics/BlockLength:
  Max: 45

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10
