AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/unicorn.rb'
    - 'bin/setup'
    - 'vendor/**/*'
    - 'test/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.3
  DisplayCopNames: true

Lint/EndAlignment:
  Enabled: false

Style/CaseIndentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ElseAlignment:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/ParenthesesAroundCondition:
  Enabled: false

# allow "self.new"
Style/RedundantSelf:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/SpaceBeforeFirstArg:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails:
  Enabled: true

# ----------------

# Configuration parameters: CountComments.
Metrics/ClassLength:
  Exclude:
    - 'app/models/*'
    - 'app/controllers/viewer_controller.rb'
    - 'lib/arcana_searcher.rb'
    - 'lib/arcana_importer.rb'
    - 'lib/arcana_cache.rb'

# Configuration parameters: Include.
Rails/Output:
  Exclude:
    - 'lib/arcana_importer.rb'

Metrics/AbcSize:
  Max: 60
  Exclude:
    - 'lib/arcana_searcher.rb'
    - 'lib/arcana_importer.rb'

Metrics/CyclomaticComplexity:
  Max: 44

# Configuration parameters: AllowURI, URISchemes.
Metrics/LineLength:
  Max: 140
  Exclude:
    - 'lib/arcana_importer.rb'

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 60
  Exclude:
    - 'lib/arcana_searcher.rb'
    - 'lib/arcana_importer.rb'

Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'lib/arcana_searcher.rb'
    - 'lib/arcana_importer.rb'

# Configuration parameters: Width.
Style/IndentationWidth:
  Exclude:
    - 'lib/arcana_searcher.rb'
