-
  ver: 20140723-beta
  body: 「海風の港」で追加されたアルカナに対応
-
  ver: 20140722-beta
  body: 「海風の港」のSSRを追加
-
  ver: 20140718a-beta
  body: スキル検索を追加
-
  ver: 20140718-beta
  body: 2部への対応開始
-
  ver: 20140717a-beta
  body: 初回アクセス時のチュートリアルを追加
-
  ver: 20140717-beta
  body: スキルの表示に暫定対応
-
  ver: 20140716-beta
  body: 解像度に応じて横に並べる数を変更
-
  ver: 20140715a-beta
  body: スマフォ等の解像度でも閲覧だけ可能に
-
  ver: 20140715-beta
  body: 初公開版
