-
  ver: 20151226
  date: 2015/12/26
  body: エイラとズフラスのデータを追加 / ファティマの上方修正に対応
-
  ver: 20151223
  date: 2015/12/23
  body: パーティー編集モードにもソート機能を追加
-
  ver: 20151220
  date: 2015/12/20
  body: 2部7章のSRとRのデータを修正
-
  ver: 20151219
  date: 2015/12/19
  body: キャロルとリーアのデータを追加 / 2部7章のSSRのデータを修正
-
  ver: 20151215
  date: 2015/12/15
  body: 2部7章のデータを仮登録
-
  ver: 20151212
  date: 2015/12/12
  body: ダスティver.2のデータを追加 / 検索フォームをコンパクトに修正
-
  ver: 20151206
  date: 2015/12/06
  body: 2パターンあるスキルの表示に対応
-
  ver: 20151204
  date: 2015/12/04
  body: 聖剣伝説コラボの闇フェス分を追加 / シジマを追加
-
  ver: 20151129
  date: 2015/11/29
  body: 聖剣伝説コラボの光フェス分を追加
-
  ver: 20151128
  date: 2015/11/28
  body: 名前から検索を追加 / サクヤのデータを追加
-
  ver: 20151123
  date: 2015/11/23
  body: リーニャver.2のデータを正式版に修正
-
  ver: 20151120
  date: 2015/11/20
  body: 相剋の精霊島関連のデータを修正 / ソフィーのデータを追加
-
  ver: 20151119
  date: 2015/11/19
  body: 相剋の精霊島関連のデータを部分的に追加
-
  ver: 20151115
  date: 2015/11/15
  body: 名前が長い場合にデザインが崩れる問題に対応 / 抜けていたデータを追加
-
  ver: 20151107
  date: 2015/11/07
  body: キララネのデータを追加 / ver2.5.2のSSR上方修正に対応
-
  ver: 20151103
  date: 2015/11/03
  body: ナナイのデータを追加 / 地形系アビリティを細分化
-
  ver: 20151101
  date: 2015/11/01
  body: リュドミラのデータを追加 / アビリティの分類を細分化
-
  ver: 20151030
  date: 2015/10/30
  body: アトリエ・アーランドシリーズコラボのデータを追加
-
  ver: 20151027
  date: 2015/10/27
  body: シュガーのデータを追加
-
  ver: 20151026
  date: 2015/10/26
  body: テルーのデータを追加 / ザレンのアビリティを修正
-
  ver: 20151018
  date: 2015/10/18
  body: 専用武器アビリティの表示と検索に対応
-
  ver: 20151017
  date: 2015/10/17
  body: アビリティ検索を見直して細分化 / 竜徹フェスのフリージア追加と強化に対応
-
  ver: 20151010
  date: 2015/10/10
  body: 九領の追加分に対応 / アビリティ検索の不具合を修正
-
  ver: 20151005
  date: 2015/10/05
  body: ライラックのデータを追加 / 鉄煙のSRのアビリティを追加
-
  ver: 20150929
  date: 2015/09/29
  body: 鉄煙の大陸のRとHNをわかる範囲で追加
-
  ver: 20150927
  date: 2015/09/27
  body: 鉄煙の大陸のSSRとSRをわかる範囲で追加
-
  ver: 20150921
  date: 2015/09/21
  body: パーティー保存機能を追加
-
  ver: 20150920
  date: 2015/09/20
  body: ソニアとキリカのアビリティを追加 / 歌・踊りの効果を細分化
-
  ver: 20150918
  date: 2015/09/18
  body: シャイニング・レゾナンスコラボのデータを修正
-
  ver: 20150914
  date: 2015/09/14
  body: シャイニング・レゾナンスコラボのデータを仮追加
-
  ver: 20150905
  date: 2015/09/05
  body: 罪の大陸の追加分とシュゾンのデータを追加
-
  ver: 20150829
  date: 2015/08/29
  body: フーコの夏祭り関連データを完全版に修正
-
  ver: 20150827
  date: 2015/08/27
  body: フーコの夏祭り関連データを仮登録
-
  ver: 20150824
  date: 2015/08/24
  body: 検索結果から直接お気に入りに追加できるように修正 / カタリスの調整に対応
-
  ver: 20150815
  date: 2015/08/15
  body: スキルの表示を新形式に変更 / ロサビスのデータを完全版に修正
-
  ver: 20150809
  date: 2015/08/09
  body: 絆アビリティを新形式に完全移行 / ロサビスのデータを一部登録
-
  ver: 20150807
  date: 2015/08/07
  body: ロザリアのデータを追加
-
  ver: 20150801
  date: 2015/08/01
  body: バスマ・イビサム・ツヅミのデータを追加 / 絆アビリティの一部を新形式で登録（まだ作業中）
-
  ver: 20150726
  date: 2015/07/26
  body: 新しい形式で全アビリティに対応（絆アビリティは作業中） / 最近のデータを完全版に修正
-
  ver: 20150725
  date: 2015/07/25
  body: ブレイブフロンティアコラボのデータを追加 / 薄命の大陸のデータを完全版に修正
-
  ver: 20150719
  date: 2015/07/19
  body: ver2にシステムをバージョンUP / ケ者チェインストーリーフェス関連のアルカナを追加
-
  ver: 20150713
  date: 2015/07/13
  body: 2周年記念フェスのデータとSSRナックルを追加
-
  ver: 20150705
  date: 2015/07/05
  body: レガレのデータを追加 / 一部アルカナのデータを更新
-
  ver: 20150624
  date: 2015/06/24
  body: 薄命の大陸と魔神タクリタン関連のアルカナを仮登録
-
  ver: 20150607
  date: 2015/06/07
  body: ファティマのデータを追加 / フェス限定SSRのアビリティ修正に対応
-
  ver: 20150604
  date: 2015/06/04
  body: ガーランドのデータを追加
-
  ver: 20150530
  date: 2015/05/30
  body: 迷宮山脈とゴブリンの王国関連のデータを追加
-
  ver: 20150517
  date: 2015/05/17
  body: キャンディス/バラクーダ/コラールのデータを追加
-
  ver: 20150503
  date: 2015/05/03
  body: モルシェラのデータを追加
-
  ver: 20150501
  date: 2015/05/01
  body: アルフィンのデータを正式版に修正
-
  ver: 20150425
  date: 2015/04/25
  body: シャウナのデータを追加
-
  ver: 20150419
  date: 2015/04/19
  body: アニメ版ノエルのデータを追加
-
  ver: 20150413
  date: 2015/04/13
  body: 大海チェインストーリーフェスのデータを追加 / 細かいバグを修正
-
  ver: 20150404
  date: 2015/04/04
  body: カスガのデータを追加
-
  ver: 20150330
  date: 2015/03/30
  body: ラファーガのデータを正式版に修正
-
  ver: 20150327
  date: 2015/03/27
  body: 討伐戦フェスのデータを追加
-
  ver: 20150322
  date: 2015/03/22
  body: ルーノのデータを追加
-
  ver: 20150317
  date: 2015/03/17
  body: 七つの大罪コラボのデータを追加
-
  ver: 20150315a
  date: 2015/03/15
  body: セガ・マークIIIを追加
-
  ver: 20150315
  date: 2015/03/15
  body: 罪の大陸のR/HNを追加 / 一部アビリティ分類を修正
-
  ver: 20150312
  date: 2015/03/12
  body: 罪の大陸の一部アビリティを修正 / 一部スキル分類を修正
-
  ver: 20150308
  date: 2015/03/08
  body: 罪の大陸のSSR/SRをわかっている範囲で追加 / スキルとアビリティの分類を修正
-
  ver: 20150302
  date: 2015/03/02
  body: エールイを追加 / 一部スキルの効果を細分化 / 一部アルカナのデータを修正
-
  ver: 20150227
  date: 2015/02/27
  body: ディードver.2のデータを正式版に修正 / マスターシステムを追加
-
  ver: 20150221
  date: 2015/02/21
  body: 羽ばたく自由の鷹関連のデータを追加
-
  ver: 20150215
  date: 2015/02/15
  body: チェンクロラジオコラボのデータを追加
-
  ver: 20150207
  date: 2015/02/07
  body: ドゥルセのデータを追加
-
  ver: 20150206
  date: 2015/02/06
  body: データベースモードにソートボタンを追加 / 各ボタンにアイコンを追加
-
  ver: 20150202
  date: 2015/02/02
  body: ヴェスパのデータを追加
-
  ver: 20150128
  date: 2015/01/28
  body: アルカナ詳細に攻略Wikiへのリンクを追加
-
  ver: 20150127a
  date: 2015/01/27
  body: 「お気に入り」機能を追加
-
  ver: 20150127
  date: 2015/01/27
  body: タリビクのデータを正式版に修正
-
  ver: 20150124
  date: 2015/01/24
  body: 検索履歴の保存と履歴からの再検索を追加
-
  ver: 20150123
  date: 2015/01/23
  body: ファルナーズのデータを追加
-
  ver: 20150121
  date: 2015/01/21
  body: 「データベースモード」をβ版として公開 / スマートフォンでの閲覧性を向上
-
  ver: 20150117
  date: 2015/01/17
  body: アイレのデータを追加 / 一部アビリティの分類を見直し
-
  ver: 20150114
  date: 2015/01/14
  body: 九領外伝フェスのデータを追加
-
  ver: 20150113
  date: 2015/01/13
  body: スキルの追加効果を正しく検索できない問題に対応
-
  ver: 20150107
  date: 2015/01/07
  body: 操作レスポンスの改善 / 細かなデザイン調整
-
  ver: 20150106
  date: 2015/01/06
  body: 検索時のページ送りUIを改善 / その他細かなデザイン調整
-
  ver: 20150102
  date: 2015/01/02
  body: ツガルとメリオのデータを追加
-
  ver: 20141231
  date: 2014/12/31
  body: フロガビトゥスのデータを正式版に修正
-
  ver: 20141226
  date: 2014/12/26
  body: ギンとドルテのデータを追加
-
  ver: 20141225
  date: 2014/12/25
  body: アルカナのコストや絆コストによる検索を追加
-
  ver: 20141224
  date: 2014/12/24
  body: 検索結果のアルカナに絆コストの表示を追加
-
  ver: 20141223
  date: 2014/12/23
  body: 「多重詠唱」「連撃」のような多段スキルに対応
-
  ver: 20141219
  date: 2014/12/19
  body: リンセとニコルのデータを追加
-
  ver: 20141219a
  date: 2014/12/19
  body: β表記を削除
-
  ver: 20141215-beta
  date: 2014/12/15
  body: 「ケ者」のデータを一部更新
-
  ver: 20141212-beta
  date: 2014/12/12
  body: 2部3章の酒場で出現しないアルカナの入手先を修正 / 新規入手先で検索できない問題を修正
-
  ver: 20141211-beta
  date: 2014/12/11
  body: 「ケ者」のHNを可能な範囲で追加 / 一部スキルの分類を見直し
-
  ver: 20141209-beta
  date: 2014/12/09
  body: 「ケ者」のRを可能な範囲で追加
-
  ver: 20141208-beta
  date: 2014/12/08
  body: 「ケ者」のSSRとSRを追加
-
  ver: 20141208a-beta
  date: 2014/12/08
  body: ドリームキャストを追加
-
  ver: 20141207-beta
  date: 2014/12/07
  body: 閃の軌跡IIコラボのデータを追加
-
  ver: 20141204-beta
  date: 2014/12/04
  body: ver2.2アップデートの既存アビリティ調整に対応
-
  ver: 20141202-beta
  date: 2014/12/02
  body: シュラッカのデータを追加
-
  ver: 20141127-beta
  date: 2014/11/27
  body: シェスメトのデータを正式版に修正
-
  ver: 20141123-beta
  date: 2014/11/23
  body: 秘宝の迷宮関連のデータを追加
-
  ver: 20141115-beta
  date: 2014/11/15
  body: エフィメラのデータを追加
-
  ver: 20141110-beta
  date: 2014/11/10
  body: キャスのデータを追加
-
  ver: 20141103-beta
  date: 2014/11/03
  body: セラカとバリキのデータを追加
-
  ver: 20141030-beta
  date: 2014/10/30
  body: 「最後に作ったパーティーメンバー」をメンバー欄へ呼び出す形に修正
-
  ver: 20141029-beta
  date: 2014/10/29
  body: サーバ移転に伴いURLを変更
-
  ver: 20141028-beta
  date: 2014/10/28
  body: 「使い方」に説明動画を追加
-
  ver: 20141028a-beta
  date: 2014/10/28
  body: 公式でアナウンスされた所属と絆アビリティの修正に対応
-
  ver: 20141025-beta
  date: 2014/10/25
  body: シャーリーとゲームギアのデータを追加 / 「必殺技威力上昇」の分類を修正
-
  ver: 20141024-beta
  date: 2014/10/24
  body: 「履歴呼び出し」を追加（最後に使った/最後に作ったパーティーメンバー/etc...）
-
  ver: 20141023-beta
  date: 2014/10/23
  body: 絆システムに対応したパーティー編成を可能に / その他、多数の修正（詳細は履歴にて）
-
  ver: 20141023a-beta
  date: 2014/10/23
  body: すでにセット済みのアルカナに新しいアルカナをドロップすることで、絆と置き換えの選択を可能に
-
  ver: 20141023b-beta
  date: 2014/10/23
  body: 絆システム対応にあわせ、パーティー編成コードの仕様を変更（旧コードも利用可能）
-
  ver: 20141023c-beta
  date: 2014/10/23
  body: 初期表示を2部の義勇軍メンバーに変更
-
  ver: 20141023d-beta
  date: 2014/10/23
  body: 検索結果のソート順を変更
-
  ver: 20141023e-beta
  date: 2014/10/23
  body: アルカナのドラッグ中、操作説明を表示するように
-
  ver: 20141023f-beta
  date: 2014/10/23
  body: ヘルプ周りの文章を全体に整理
-
  ver: 20141017-beta
  date: 2014/10/17
  body: モノクマのデータを正式版に / 絆アビリティ名が判明したアルカナの修正
-
  ver: 20141016-beta
  date: 2014/10/16
  body: 絶対絶望少女コラボとセガハードコラボのアルカナを追加
-
  ver: 20141009-beta
  date: 2014/10/09
  body: メガドライブを追加
-
  ver: 20141008-beta
  date: 2014/10/08
  body: サマリーとメイン画面にも絆アビリティを表示 / 同一人物を一緒に登録できないように修正
-
  ver: 20141007-beta
  date: 2014/10/07
  body: 絆アビリティの表示と検索を追加
-
  ver: 20141003a-beta
  date: 2014/10/03
  body: アビリティの効果をさらに細かく分離
-
  ver: 20141003-beta
  date: 2014/10/03
  body: アビリティ発動条件の「敵が状態異常時」を細かく分離
-
  ver: 20141001-beta
  date: 2014/10/01
  body: 「所属」情報の追加と検索＆リングSSRパメラスを追加
-
  ver: 20140930-beta
  date: 2014/09/30
  body: ver2.1アップデートで精霊島に追加されたアルカナを登録
-
  ver: 20140926-beta
  date: 2014/09/26
  body: 「最近使ったアルカナ」での絞り込みを可能に
-
  ver: 20140925-beta
  date: 2014/09/25
  body: 入手先を細かく分類し直し、検索可能に
-
  ver: 20140924-beta
  date: 2014/09/24
  body: アビリティの状態異常や属性で細かい検索を可能に
-
  ver: 20140923-beta
  date: 2014/09/23
  body: スキルの検索条件にコストと追加効果を追加
-
  ver: 20140921-beta
  date: 2014/09/21
  body: スキルの追加効果表記を追加
-
  ver: 20140920-beta
  date: 2014/09/20
  body: ウィルベルのデータを正式版に修正
-
  ver: 20140917-beta
  date: 2014/09/17
  body: アトリエ（黄昏）コラボと新リングガチャSSRを追加
-
  ver: 20140912-beta
  date: 2014/09/12
  body: デザインを整理（サマリー情報の増加/検索UIの修正/etc...）
-
  ver: 20140910-beta
  date: 2014/09/10
  body: 「夜明けの大海」のHNを追加
-
  ver: 20140905-beta
  date: 2014/09/05
  body: 「夜明けの大海」のRを追加 / アビリティ分類を見直し
-
  ver: 20140904-beta
  date: 2014/09/04
  body: 「夜明けの大海」のSSRとSRを部分的に追加 / ミジョカのアビリティを登録 / スキル・アビリティ分類を見直し
-
  ver: 20140903-beta
  date: 2014/09/03
  body: 刃牙コラボのアルカナを追加
-
  ver: 20140901-beta
  date: 2014/09/01
  body: ラジオコラボ（ユカチ・カナーン）とソリティーを追加 / アビリティ分類追加
-
  ver: 20140830-beta
  date: 2014/08/30
  body: 一部アルカナの入手先を「戦の年代記」に変更 / 表示項目の調整
-
  ver: 20140828-beta
  date: 2014/08/28
  body: 複合的なアビリティの表示と検索に対応
-
  ver: 20140827-beta
  date: 2014/08/27
  body: ツル姫のデータを正式版に修正
-
  ver: 20140827a-beta
  date: 2014/08/27
  body: 「2部限定」検索条件を廃止
-
  ver: 20140825-beta
  date: 2014/08/25
  body: 「ツル姫と夏祭り」関連アルカナの情報を修正
-
  ver: 20140822-beta
  date: 2014/08/22
  body: 「ツル姫と夏祭り」で追加されたアルカナを仮登録
-
  ver: 20140819-beta
  date: 2014/08/19
  body: 編集モードからのアルカナ詳細呼び出しを可能に
-
  ver: 20140817-beta
  date: 2014/08/17
  body: アグダラのデータを正式版に更新
-
  ver: 20140813-beta
  date: 2014/08/13
  body: オルオレータのデータを正式版に更新
-
  ver: 20140812-beta
  date: 2014/08/12
  body: アビリティからの検索を実装
-
  ver: 20140810-beta
  date: 2014/08/10
  body: アグダラとオルオレータの名称のみを登録
-
  ver: 20140808-beta
  date: 2014/08/08
  body: アルカナ詳細にアビリティを追加
-
  ver: 20140805-beta
  date: 2014/08/05
  body: パトリシア（ver2）のデータを追加
-
  ver: 20140801-beta
  date: 2014/08/01
  body: マリーダの情報を追加 / 細かいデータ修正
-
  ver: 20140729-beta
  date: 2014/07/29
  body: ATK/HP/職業データを追加 / モアネットを登録
-
  ver: 20140729a-beta
  date: 2014/07/29
  body: メンバーエリアのアルカナをドラッグアンドドロップした際、移動ではなく入れ替えに変更
-
  ver: 20140725a-beta
  date: 2014/07/25
  body: アルカナ詳細を表示可能に / その他バグ修正
-
  ver: 20140725-beta
  date: 2014/07/25
  body: 「モアネット救援支援フェス」で追加されたアルカナを登録
-
  ver: 20140724-beta
  date: 2014/07/24
  body: 画像の組み込みを含め、一部のデザインを見直し
-
  ver: 20140723-beta
  date: 2014/07/23
  body: 「海風の港」で追加されたアルカナに対応
-
  ver: 20140722-beta
  date: 2014/07/22
  body: 「海風の港」のSSRを追加
-
  ver: 20140718a-beta
  date: 2014/07/18
  body: スキル検索を追加
-
  ver: 20140718-beta
  date: 2014/07/18
  body: 2部への対応開始
-
  ver: 20140717a-beta
  date: 2014/07/17
  body: 初回アクセス時のチュートリアルを追加
-
  ver: 20140717-beta
  date: 2014/07/17
  body: スキルの表示に暫定対応
-
  ver: 20140716-beta
  date: 2014/07/16
  body: 解像度に応じて横に並べる数を変更
-
  ver: 20140715a-beta
  date: 2014/07/15
  body: スマフォ等の解像度でも閲覧だけ可能に
-
  ver: 20140715-beta
  date: 2014/07/15
  body: 初公開版
