api:
  recently: 32
  pt_version: 3
mail:
  use: <%= ENV['MAIL_USE'].to_i > 0 ? true : false %>
  from: <%= ENV['MAIL_FROM'] %>
  admin:
    to: <%= ENV['MAIL_ADMIN_TO'] %>
  delivery_method: <%= ENV['MAIL_METHOD'] %>
redis:
  host: <%= ENV['REDIS_HOST'] %>
  port: <%= ENV['REDIS_PORT'] %>
  db: <%= ENV['REDIS_DB'] %>
