arcanas: &arcanas
  jobs: F K P A M
  rarity: 5
  weapons: Sl Bl Pi Ar He Ma Pu
  recently: 24
  hometowns: unknown guildtown holytown academy mountain oasis forest volcano demon collaboration forest-sea
  sources: other guildtown holytown academy mountain oasis forest volcano ring demon event collaboration forest-sea
  growths: fast normal slow
  additions: 1 2
  data_version: 20140825
  pt_version: 1

production:
  app_path: "http://app.parrot-studio.com/ccpts/"
  <<: *arcanas
development:
  app_path: "http://localhost:3000/"
  <<: *arcanas
test:
  app_path: "http://localhost:3000/"
  <<: *arcanas
