arcanas: &arcanas
  jobs: F K P A M
  rarity: 5
  weapons: Sl Bl Pi Ar He Ma Pu Gu Sh
  recently: 24
  pt_version: 1

production:
  app_path: "http://app.parrot-studio.com/ccpts/"
  cache: true
  <<: *arcanas
development:
  app_path: "http://localhost:3000/"
  cache: false
  <<: *arcanas
test:
  app_path: "http://localhost:3000/"
  cache: false
  <<: *arcanas
