arcanas: &arcanas
  jobs: F K P A M
  rarity: 5
  weapons: S B P A H M
  recently: 12
  hometowns: subcity church academy mountain oasis forest volcano ring demon event collaboration
  data_version: 20140703
  pt_version: 1

production:
  app_path: "http://app.parrot-studio.com/ccpt/"
  <<: *arcanas
development:
  app_path: "http://localhost:3000/"
  <<: *arcanas
test:
  app_path: "http://localhost:3000/"
  <<: *arcanas
