arcanas: &arcanas
  recently: 24
  pt_version: 2

production:
  cache: true
  mail: true
  <<: *arcanas
development:
  cache: false
  mail: true
  <<: *arcanas
test:
  cache: false
  mail: false
  <<: *arcanas
