arcanas: &arcanas
  jobs: F K P A M
  rarity: 5

production:
  app_path: "http://cc.parrot-studio.com/pt/"
  <<: *arcanas
development:
  app_path: "http://localhost:3000/pt/"
  <<: *arcanas
test:
  app_path: "http://localhost:3000/pt/"
  <<: *arcanas
