arcanas: &arcanas
  jobs: F K P A M
  rarity: 5
  data_version: 20140624
  pt_version: 1

production:
  app_path: "http://app.parrot-studio.com/cc/"
  <<: *arcanas
development:
  app_path: "http://localhost:3000/"
  <<: *arcanas
test:
  app_path: "http://localhost:3000/"
  <<: *arcanas
