api:
  recently: 24
  pt_version: 2
mail:
  use: <%= ENV['MAIL_USE'].to_i > 0 ? true : false %>
  from: <%= ENV['MAIL_FROM'] %>
  admin:
    to: <%= ENV['MAIL_ADMIN_TO'] %>
  delivery_method: <%= ENV['MAIL_METHOD'] %>
