arcanas: &arcanas
  jobs: F K P A M
  rarity: 5
  weapons: Sl Bl Pi Ar He Ma Pu Gu Sh
  recently: 24
  pt_version: 2

production:
  cache: true
  <<: *arcanas
development:
  cache: false
  <<: *arcanas
test:
  cache: false
  <<: *arcanas
